// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fastqCpp
List fastqCpp(std::string argv);
RcppExport SEXP fastqc_fastqCpp(SEXP argvSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    std::string argv = Rcpp::as<std::string >(argvSEXP);
    List __result = fastqCpp(argv);
    return Rcpp::wrap(__result);
END_RCPP
}
