# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastqCpp <- function(argv, sampled) {
    .Call('fastqc_fastqCpp', PACKAGE = 'fastqc', argv, sampled)
}

trimmoCpp <- function(inp1, minlen, crop, headcrop, slidingwindow, slidingwindowlen) {
    .Call('fastqc_trimmoCpp', PACKAGE = 'fastqc', inp1, minlen, crop, headcrop, slidingwindow, slidingwindowlen)
}

